"""
Generate same-speaker code-switched EN/JA audio + frame-level language labels.

Uses XTTS v2 (Coqui) with voice cloning. Code-switched sentences are generated
as two full-sentence renders with the same cloned speaker:

  * An English render uses language="en" and converts Japanese spans to romaji.
  * A Japanese render uses language="ja" and the original mixed-script text.
  * The final clip stitches English spans from the English render and Japanese
    spans from the Japanese render. Pure single-language rows only need one
    render.

Span boundaries (for frame-level language labels) are recovered with forced
alignment: torchaudio's MMS_FA aligner matches the audio against the known
romanized transcript and yields word-level timestamps. Alignment also tells us
where real speech starts/ends, which trims XTTS's trailing babble/noise —
the classic end-of-clip hallucination — from every generated render.

Earlier versions stitched per-span mini-clips with a crossfade. That fails
badly: XTTS degenerates on short text fragments (babble, multi-second silence
padding), and stitching produces choppy prosody and loudness jumps. This script
only stitches cuts from full-sentence renders.

CSV format (no header by default; pass --has-header if yours has one):
    path/to/output.wav | the sentence to encode, 日本語 included
    manual/... rows are recorded clips and are ignored for synthesis.

Outputs per row:
    {out-root}/{path}.wav     — mono 16-bit PCM at TARGET_SR
    {out-root}/{path}.json    — span boundaries + frame-level language labels

Sidecar JSON shape:
    {
      "audio_path": "...",
      "sentence": "...",
      "sample_rate": 16000,
      "duration_ms": 2345,
      "reference_speaker": "ref_0037.wav",
      "tts_language": "stitched",
      "alignment": "forced-dual",     # or "partial-fallback-dual"
      "spans": [
        {"lang": "en", "text": "Hello,", "start_ms": 0, "end_ms": 850,
         "start_sample": 0, "end_sample": 13600},
        ...
      ],
      "frame_rate_hz": 50,
      "num_frames": 117,
      "frame_labels": "eeee...jjjj..."   # 'e'=EN, 'j'=JA, 'a'=ambiguous boundary
    }

Requirements:
    uv add "coqui-tts[codec,ja]" soundfile python-dotenv numpy torch torchaudio
    uv add fugashi pykakasi unidic-lite

License caveat: XTTS v2 ships under the Coqui Public Model License (CPML) —
non-commercial use only. Audio generated by this script is fine for research
and training internal evaluation models; if your final LID router will ship
commercially, plan to regenerate the training set with a permissively-licensed
backend (or accept that the audio data lineage may limit downstream rights)
before launch.
"""

from __future__ import annotations

import argparse
import csv
import json
import multiprocessing as mp
import random
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

import numpy as np
import soundfile as sf
import torch
import torchaudio
from dotenv import load_dotenv
from fugashi import Tagger
from pykakasi import kakasi
from TTS.api import TTS

load_dotenv()  # Parity with the rest of your project; not consumed here.

# ---- Configuration ----------------------------------------------------------

XTTS_MODEL = "tts_models/multilingual/multi-dataset/xtts_v2"
XTTS_SR = 24_000
TARGET_SR = 16_000  # wav2vec2-base expects 16 kHz mono
FRAME_RATE_HZ = 50  # wav2vec2-base outputs 50 frames/sec
FRAME_STRIDE = TARGET_SR // FRAME_RATE_HZ  # 320 samples per frame
CROSSFADE_MS = 25

# Speech-edge padding kept when trimming lead/tail non-speech.
TRIM_PAD_MS = 60
TRIM_THRESH = 0.02  # energy-trim fallback: fraction of peak counted as silence

# Degenerate-output detection. XTTS occasionally babbles/hallucinates,
# producing audio far longer than the text warrants. If a generation exceeds
# the expected duration budget, resynthesize at lower temperature and keep
# the best candidate.
MAX_ATTEMPTS = 3
ATTEMPT_TEMPERATURES = [0.7, 0.5, 0.35]
CHARS_PER_SEC = {"en": 13.0, "ja": 7.0}  # rough speaking rates
TTS_CHAR_LIMITS = {"ja": 70}  # XTTS warns/truncates Japanese text above 71 chars.
CHUNK_BREAK_RE = re.compile(r"([。！？!?、,;；:：]|\s+)")

LANG_TO_CHAR = {"en": "e", "ja": "j"}

# Unicode ranges for Japanese script. ASCII letters cover English.
JA_CHAR_RE = re.compile(
    r"[぀-ゟ"  # Hiragana
    r"゠-ヿ"  # Katakana
    r"一-鿿"  # CJK Unified Ideographs (Kanji)
    r"㐀-䶿"  # CJK Extension A
    r"ｦ-ﾟ]"  # Halfwidth Katakana
)
LATIN_CHAR_RE = re.compile(r"[A-Za-z]")
ROMAJI_TOKEN_RE = re.compile(r"[a-z0-9']+")


def _expected_duration_s(text: str, lang: str) -> float:
    return max(len(text) / CHARS_PER_SEC[lang], 0.4)


def seed_everything(seed: int) -> None:
    """Seed Python, NumPy, and Torch RNGs for reproducible synthesis."""
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)
    if hasattr(torch.backends, "cudnn"):
        torch.backends.cudnn.benchmark = False
        torch.backends.cudnn.deterministic = True
    try:
        torch.use_deterministic_algorithms(True, warn_only=True)
    except TypeError:
        torch.use_deterministic_algorithms(True)


# ---- Span detection ---------------------------------------------------------


@dataclass
class Span:
    text: str
    lang: str  # "en" or "ja"


@dataclass
class RenderResult:
    lang: str
    text: str
    audio: np.ndarray
    bounds: list[int]
    alignment: str


@dataclass
class SynthesisResult:
    audio: np.ndarray
    spans: list[dict]
    tts_language: str
    alignment: str
    renders: dict[str, dict]
    render_audio: dict[str, np.ndarray]


def detect_spans(sentence: str) -> list[Span]:
    """Split a sentence into contiguous EN / JA runs.

    Punctuation, digits, and whitespace attach to the preceding language span
    (or the next one if they lead the sentence) so trailing commas, question
    marks, and 。 stay with the span that produced them — TTS prosody depends
    on this.
    """
    char_lang = []
    for ch in sentence:
        if JA_CHAR_RE.match(ch):
            char_lang.append("ja")
        elif LATIN_CHAR_RE.match(ch):
            char_lang.append("en")
        else:
            char_lang.append("neutral")

    first_real = next((lang for lang in char_lang if lang != "neutral"), "en")
    resolved = []
    last_real = first_real
    for lang in char_lang:
        if lang == "neutral":
            resolved.append(last_real)
        else:
            last_real = lang
            resolved.append(lang)

    spans: list[Span] = []
    buf = ""
    cur = resolved[0] if resolved else "en"
    for ch, lang in zip(sentence, resolved):
        if lang == cur:
            buf += ch
        else:
            spans.append(Span(text=buf, lang=cur))
            buf = ch
            cur = lang
    if buf:
        spans.append(Span(text=buf, lang=cur))

    return [Span(text=s.text.strip(), lang=s.lang) for s in spans if s.text.strip()]


# ---- Romanization -----------------------------------------------------------


def _append_romaji_tokens(tokens: list[str], text: str) -> None:
    token = text.lower()
    if token == "'" and tokens:
        tokens[-1] += "'"
        return

    matches = ROMAJI_TOKEN_RE.findall(token)
    if not matches:
        return

    if tokens and tokens[-1].endswith("'"):
        tokens[-1] += matches[0]
        tokens.extend(matches[1:])
        return

    tokens.extend(matches)


def _romanize_japanese_text(text: str, tagger: Tagger, converter) -> str:
    tokens: list[str] = []
    for token in tagger(text):
        romaji = "".join(item["hepburn"] for item in converter.convert(token.surface))
        for romaji_part in romaji.split():
            _append_romaji_tokens(tokens, romaji_part)
    return " ".join(tokens)


def _render_text_for_language(
    sentence: str,
    spans: list[Span],
    lang: str,
    tagger: Tagger,
    converter,
) -> str:
    if lang == "ja":
        return sentence

    parts = [
        _romanize_japanese_text(span.text, tagger, converter) if span.lang == "ja" else span.text for span in spans
    ]
    return " ".join(part for part in parts if part.strip())


def _split_tts_text(text: str, lang: str) -> list[str]:
    """Split render text before it reaches XTTS's per-language character cap."""
    limit = TTS_CHAR_LIMITS.get(lang)
    if limit is None or len(text) <= limit:
        return [text]

    chunks: list[str] = []
    current = ""

    for part in CHUNK_BREAK_RE.split(text):
        if not part:
            continue
        candidate = current + part
        if len(candidate) <= limit:
            current = candidate
            continue
        if current.strip():
            chunks.append(current.strip())
            current = ""
        if len(part) <= limit:
            current = part
            continue
        for start in range(0, len(part), limit):
            piece = part[start : start + limit].strip()
            if piece:
                chunks.append(piece)

    if current.strip():
        chunks.append(current.strip())

    over_limit = [chunk for chunk in chunks if len(chunk) > limit]
    if over_limit:
        raise ValueError(f"cannot split {lang} TTS text below {limit} chars: {over_limit[0]!r}")
    return chunks


# ---- Audio utilities --------------------------------------------------------


def _resample(audio: np.ndarray, src_sr: int, dst_sr: int) -> np.ndarray:
    """Linear resample. Swap to librosa.resample / torchaudio for higher quality."""
    if src_sr == dst_sr or audio.size == 0:
        return audio
    duration = audio.size / src_sr
    dst_samples = int(round(duration * dst_sr))
    x_src = np.linspace(0, duration, audio.size, endpoint=False)
    x_dst = np.linspace(0, duration, dst_samples, endpoint=False)
    return np.interp(x_dst, x_src, audio).astype(np.float32)


def _peak_normalize(audio: np.ndarray, peak: float = 0.95) -> np.ndarray:
    if audio.size == 0:
        return audio
    m = float(np.max(np.abs(audio)))
    if m < 1e-6:
        return audio
    return (audio * (peak / m)).astype(np.float32)


def _trim_silence(
    audio: np.ndarray,
    sr: int = TARGET_SR,
    thresh: float = TRIM_THRESH,
    pad_ms: int = TRIM_PAD_MS,
) -> np.ndarray:
    """Energy-based lead/tail silence trim (fallback when alignment fails)."""
    if audio.size == 0:
        return audio
    level = float(np.max(np.abs(audio))) * thresh
    if level <= 0:
        return audio
    voiced = np.flatnonzero(np.abs(audio) >= level)
    if voiced.size == 0:
        return audio
    pad = int(sr * pad_ms / 1000)
    start = max(int(voiced[0]) - pad, 0)
    end = min(int(voiced[-1]) + pad, audio.size)
    return audio[start:end]


def _find_lang_at(center: int, spans: list[tuple[int, int, str]]) -> str:
    for start, end, lang in spans:
        if start <= center < end:
            return lang
    return spans[-1][2] if spans else "en"


def _frame_labels(
    spans: list[tuple[int, int, str]],
    total_samples: int,
    boundary_ambig_ms: int = 0,
) -> str:
    """One char per frame at FRAME_RATE_HZ.

    For each frame, the label is the language of the span containing the
    frame's center sample. If ``boundary_ambig_ms`` > 0, frames whose centers
    fall within that window of a language switch are labeled 'a' (ambiguous).
    """
    boundary_ambig_samples = int(boundary_ambig_ms * TARGET_SR / 1000)
    num_frames = (total_samples + FRAME_STRIDE - 1) // FRAME_STRIDE

    # Span boundaries = starts of spans 2..N (i.e. switch points).
    switch_points = [s[0] for s in spans[1:]]

    labels: list[str] = []
    for f in range(num_frames):
        center = f * FRAME_STRIDE + FRAME_STRIDE // 2
        if boundary_ambig_samples > 0 and any(abs(center - sp) <= boundary_ambig_samples for sp in switch_points):
            labels.append("a")
        else:
            labels.append(LANG_TO_CHAR[_find_lang_at(center, spans)])
    return "".join(labels)


# ---- Forced alignment -------------------------------------------------------


class ForcedAligner:
    """MMS_FA forced aligner: word-level timestamps for a known transcript.

    Works on romanized text (a-z + apostrophe), which matches exactly what
    XTTS's ja frontend speaks, so EN and romanized-JA words both align.
    """

    def __init__(self, device: str = "cpu"):
        self.device = device
        bundle = torchaudio.pipelines.MMS_FA
        self.model = bundle.get_model(with_star=False).to(device)
        self.tokenizer = bundle.get_tokenizer()
        self.aligner = bundle.get_aligner()
        # Exclude special tokens: "-" is the CTC blank, "*" the star token.
        self.allowed = set(bundle.get_dict(star=None).keys()) - {"-", "*"}

    def sanitize(self, word: str) -> str:
        return "".join(ch for ch in word.lower() if ch in self.allowed)

    def align(self, audio_16k: np.ndarray, words: list[str]) -> list[tuple[int, int]]:
        """Return per-word (start_sample, end_sample) in the given audio."""
        wav = torch.from_numpy(audio_16k).unsqueeze(0).to(self.device)
        with torch.inference_mode():
            emission, _ = self.model(wav)
            token_spans = self.aligner(emission[0], self.tokenizer(words))
        ratio = wav.size(1) / emission.size(1)
        return [(int(spans[0].start * ratio), int(spans[-1].end * ratio)) for spans in token_spans]


def _aligner_words(spans: list[Span], tagger: Tagger, converter) -> tuple[list[str], list[int]]:
    """Romanized words + owning-span index for a full-sentence render."""
    words: list[str] = []
    owner: list[int] = []
    for i, span in enumerate(spans):
        text = _romanize_japanese_text(span.text, tagger, converter) if span.lang == "ja" else span.text
        for w in ROMAJI_TOKEN_RE.findall(text.lower()):
            words.append(w)
            owner.append(i)
    return words, owner


def _span_boundaries(
    word_samples: list[tuple[int, int]],
    owner: list[int],
    n_spans: int,
    total_samples: int,
    expected: list[float],
) -> list[int]:
    """Boundary sample positions between consecutive spans (len = n_spans - 1).

    Each boundary is the midpoint of the gap between the last aligned word of
    span i and the first aligned word of span i+1. Spans that lost all their
    words to sanitization get boundaries interpolated from expected durations.
    """
    firsts: dict[int, int] = {}
    lasts: dict[int, int] = {}
    for (s, e), o in zip(word_samples, owner):
        firsts.setdefault(o, s)
        lasts[o] = e

    bounds: list[int | None] = []
    for i in range(n_spans - 1):
        if i in lasts and (i + 1) in firsts and lasts[i] <= firsts[i + 1]:
            bounds.append((lasts[i] + firsts[i + 1]) // 2)
        else:
            bounds.append(None)

    # Interpolate unknown boundaries proportionally to expected span durations.
    for i, b in enumerate(bounds):
        if b is not None:
            continue
        lo_i = i
        while lo_i > 0 and bounds[lo_i - 1] is None:
            lo_i -= 1
        hi_i = i
        while hi_i < len(bounds) - 1 and bounds[hi_i + 1] is None:
            hi_i += 1
        lo = bounds[lo_i - 1] if lo_i > 0 else 0
        hi = bounds[hi_i + 1] if hi_i < len(bounds) - 1 else total_samples
        # spans covered: lo_i .. hi_i+1 ; boundary i sits after span i
        w_total = sum(expected[lo_i : hi_i + 2])
        w_before = sum(expected[lo_i : i + 1])
        bounds[i] = int(lo + (hi - lo) * (w_before / w_total)) if w_total > 0 else (lo + hi) // 2
    return [int(b) for b in bounds]  # type: ignore[arg-type]


def _proportional_boundaries(total_samples: int, expected: list[float]) -> list[int]:
    total_exp = sum(expected)
    if total_exp <= 0:
        return []

    acc = 0.0
    bounds = []
    for exp in expected[:-1]:
        acc += exp
        bounds.append(int(total_samples * acc / total_exp))
    return bounds


def _clamped_edges(bounds: list[int], total_samples: int) -> list[int]:
    edges = [0]
    for bound in bounds:
        edges.append(min(max(bound, edges[-1]), total_samples))
    edges.append(total_samples)
    return edges


def _record_spans(spans: list[Span], ranges: list[tuple[int, int]]) -> list[dict]:
    records: list[dict] = []
    for span, (start_sample, end_sample) in zip(spans, ranges):
        records.append(
            {
                "lang": span.lang,
                "text": span.text,
                "start_sample": start_sample,
                "end_sample": end_sample,
                "start_ms": int(round(start_sample / TARGET_SR * 1000)),
                "end_ms": int(round(end_sample / TARGET_SR * 1000)),
            }
        )
    return records


def _stitch_chunks(
    chunks: list[np.ndarray],
    crossfade_samples: int,
) -> tuple[np.ndarray, list[tuple[int, int]]]:
    if not chunks:
        return np.zeros(0, dtype=np.float32), []

    audio = chunks[0].astype(np.float32, copy=True)
    ranges: list[tuple[int, int | None]] = [(0, None)]

    for chunk in chunks[1:]:
        chunk = chunk.astype(np.float32, copy=False)
        fade = min(crossfade_samples, audio.size // 2, chunk.size // 2)
        boundary = audio.size - fade // 2
        ranges[-1] = (ranges[-1][0], boundary)
        ranges.append((boundary, None))

        if fade > 0:
            fade_out = np.cos(np.linspace(0, np.pi / 2, fade, endpoint=False)).astype(np.float32)
            fade_in = np.sin(np.linspace(0, np.pi / 2, fade, endpoint=False)).astype(np.float32)
            overlap = audio[-fade:] * fade_out + chunk[:fade] * fade_in
            audio = np.concatenate([audio[:-fade], overlap, chunk[fade:]])
        else:
            audio = np.concatenate([audio, chunk])

    ranges[-1] = (ranges[-1][0], audio.size)
    return audio, [(start, int(end)) for start, end in ranges]


# ---- Synthesizer ------------------------------------------------------------


class XTTSCodeSwitchSynthesizer:
    """XTTS v2 wrapper: whole-sentence synthesis with cached speaker latents,
    degenerate-output retry, and alignment-based span recovery + trimming.
    """

    def __init__(self, reference_dirs: list[Path], device: str = "cuda", align_device: str = "cpu"):
        # If running headless, set COQUI_TOS_AGREED=1 before launching to
        # bypass the interactive model-license prompt on first download.
        self.tts = TTS(XTTS_MODEL)
        self.tts.to(device)
        self.model = self.tts.synthesizer.tts_model
        self.aligner = ForcedAligner(device=align_device)
        self.tagger = Tagger()
        self.kakasi = kakasi()

        exts = {".wav", ".mp3", ".flac"}
        self.references = sorted(
            p for reference_dir in reference_dirs for p in reference_dir.glob("*") if p.suffix.lower() in exts
        )
        if not self.references:
            dirs = ", ".join(str(p) for p in reference_dirs)
            raise FileNotFoundError(f"No reference clips (.wav/.mp3/.flac) found in: {dirs}")
        self._latent_cache: dict[Path, tuple] = {}

    def pick_reference(self, rng: random.Random) -> Path:
        return rng.choice(self.references)

    def _get_latents(self, ref_path: Path):
        cached = self._latent_cache.get(ref_path)
        if cached is not None:
            return cached
        # sound_norm_refs levels the reference before conditioning; several of
        # our Common Voice refs are extremely quiet (RMS < 0.01), which skews
        # the speaker latents and degrades synthesis.
        gpt, spk = self.model.get_conditioning_latents(
            audio_path=[str(ref_path)],
            sound_norm_refs=True,
        )
        self._latent_cache[ref_path] = (gpt, spk)
        return gpt, spk

    def _generate(self, text: str, lang: str, ref_path: Path, temperature: float) -> np.ndarray:
        gpt_cond_latent, speaker_embedding = self._get_latents(ref_path)
        out = self.model.inference(
            text=text,
            language=lang,
            gpt_cond_latent=gpt_cond_latent,
            speaker_embedding=speaker_embedding,
            temperature=temperature,
            repetition_penalty=10.0,
            top_k=50,
            top_p=0.85,
        )
        wav = out["wav"]
        if isinstance(wav, torch.Tensor):
            wav = wav.cpu().numpy()
        return np.asarray(wav, dtype=np.float32)

    def _generate_checked(self, text: str, lang: str, ref_path: Path, budget_s: float) -> np.ndarray:
        """Generate at 16 kHz, retrying degenerate (over-long) outputs."""
        best: np.ndarray | None = None
        for attempt in range(MAX_ATTEMPTS):
            temp = ATTEMPT_TEMPERATURES[min(attempt, len(ATTEMPT_TEMPERATURES) - 1)]
            audio = _resample(self._generate(text, lang, ref_path, temp), XTTS_SR, TARGET_SR)
            trimmed_s = _trim_silence(audio).size / TARGET_SR
            if best is None or audio.size < best.size:
                best = audio
            if trimmed_s <= budget_s:
                return audio
        print(
            f"    WARN degenerate output after {MAX_ATTEMPTS} attempts "
            f"({best.size / TARGET_SR:.1f}s, budget {budget_s:.1f}s): {text!r}",
            file=sys.stderr,
        )
        return best

    def _generate_chunks_checked(self, text: str, lang: str, ref_path: Path, budget_s: float) -> np.ndarray:
        chunks = _split_tts_text(text, lang)
        if len(chunks) == 1:
            return self._generate_checked(chunks[0], lang, ref_path, budget_s)

        audio_chunks = []
        for chunk in chunks:
            chunk_budget = max(len(chunk) / CHARS_PER_SEC[lang], 0.4) * 2.5 + 0.6
            audio_chunks.append(self._generate_checked(chunk, lang, ref_path, chunk_budget))
        return np.concatenate(audio_chunks).astype(np.float32)

    def _align_render(self, audio: np.ndarray, spans: list[Span], expected: list[float], lang: str) -> RenderResult:
        pad = int(TARGET_SR * TRIM_PAD_MS / 1000)
        alignment_mode = "forced"
        try:
            words, owner = _aligner_words(spans, self.tagger, self.kakasi)
            sanitized = [(self.aligner.sanitize(w), o) for w, o in zip(words, owner)]
            sanitized = [(w, o) for w, o in sanitized if w]
            if not sanitized:
                raise ValueError("no alignable words")
            word_samples = self.aligner.align(audio, [w for w, _ in sanitized])

            start = max(word_samples[0][0] - pad, 0)
            end = min(word_samples[-1][1] + pad, audio.size)
            audio = audio[start:end]
            word_samples = [(s - start, e - start) for s, e in word_samples]
            bounds = _span_boundaries(word_samples, [o for _, o in sanitized], len(spans), audio.size, expected)
        except Exception as e:  # noqa: BLE001 — degrade to proportional estimate
            print(f"    WARN {lang} alignment failed ({e}); using proportional spans", file=sys.stderr)
            alignment_mode = "fallback"
            audio = _trim_silence(audio)
            bounds = _proportional_boundaries(audio.size, expected)

        return RenderResult(lang=lang, text="", audio=_peak_normalize(audio), bounds=bounds, alignment=alignment_mode)

    def _synthesize_render(
        self,
        sentence: str,
        spans: list[Span],
        expected: list[float],
        lang: str,
        ref_path: Path,
    ) -> RenderResult:
        text = _render_text_for_language(sentence, spans, lang, self.tagger, self.kakasi)
        budget_base_s = max(sum(expected), len(text) / CHARS_PER_SEC[lang])
        audio = self._generate_chunks_checked(text, lang, ref_path, budget_base_s * 2.5 + 0.6)
        render = self._align_render(audio, spans, expected, lang)
        render.text = text
        return render

    def synthesize(self, sentence: str, ref_path: Path) -> SynthesisResult:
        """Return final audio, span records, and render metadata."""
        spans = detect_spans(sentence)
        if not spans:
            return SynthesisResult(
                audio=np.zeros(0, dtype=np.float32),
                spans=[],
                tts_language="en",
                alignment="none",
                renders={},
                render_audio={},
            )

        expected = [_expected_duration_s(s.text, s.lang) for s in spans]
        if all(s.lang == "en" for s in spans):
            needed_langs = ["en"]
        elif all(s.lang == "ja" for s in spans):
            needed_langs = ["ja"]
        else:
            needed_langs = ["en", "ja"]
        renders = {lang: self._synthesize_render(sentence, spans, expected, lang, ref_path) for lang in needed_langs}
        render_audio = {lang: render.audio for lang, render in renders.items()}

        empty_renders = [lang for lang, render in renders.items() if render.audio.size == 0]
        if empty_renders:
            raise ValueError("empty render(s): " + ", ".join(empty_renders))

        if len(renders) == 1:
            render = next(iter(renders.values()))
            edges = _clamped_edges(render.bounds, render.audio.size)
            ranges = list(zip(edges[:-1], edges[1:]))
            return SynthesisResult(
                audio=render.audio,
                spans=_record_spans(spans, ranges),
                tts_language=render.lang,
                alignment=render.alignment,
                renders=self._render_metadata(renders, spans),
                render_audio=render_audio,
            )

        chunks = []
        for index, span in enumerate(spans):
            render = renders[span.lang]
            edges = _clamped_edges(render.bounds, render.audio.size)
            chunks.append(render.audio[edges[index] : edges[index + 1]])

        stitched, ranges = _stitch_chunks(chunks, int(TARGET_SR * CROSSFADE_MS / 1000))
        audio = _peak_normalize(stitched)
        render_alignments = {render.alignment for render in renders.values()}
        alignment = "forced-dual" if render_alignments == {"forced"} else "partial-fallback-dual"

        return SynthesisResult(
            audio=audio,
            spans=_record_spans(spans, ranges),
            tts_language="stitched",
            alignment=alignment,
            renders=self._render_metadata(renders, spans),
            render_audio=render_audio,
        )

    def _render_metadata(self, renders: dict[str, RenderResult], spans: list[Span]) -> dict[str, dict]:
        metadata: dict[str, dict] = {}
        for lang, render in renders.items():
            edges = _clamped_edges(render.bounds, render.audio.size)
            metadata[lang] = {
                "text": render.text,
                "tts_language": render.lang,
                "alignment": render.alignment,
                "duration_ms": int(round(render.audio.size / TARGET_SR * 1000)),
                "spans": _record_spans(spans, list(zip(edges[:-1], edges[1:]))),
            }
        return metadata


# ---- CSV iteration ----------------------------------------------------------


def synthetic_folder_prefix(folder: str | None) -> str | None:
    if folder is None:
        return None

    folder = folder.strip().replace("\\", "/").strip("/")
    if not folder:
        return None

    if folder.startswith("data/synthetic/"):
        folder = folder.removeprefix("data/")
    elif folder != "synthetic" and not folder.startswith("synthetic/"):
        folder = f"synthetic/{folder}"

    return f"{folder}/"


def iter_rows(csv_path: Path, has_header: bool, synthetic_folder: str | None = None) -> Iterator[tuple[str, str]]:
    synthetic_prefix = synthetic_folder_prefix(synthetic_folder)
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter="|")
        if has_header:
            next(reader, None)
        for row in reader:
            if len(row) < 2:
                continue
            path = row[0].strip()
            text = row[1].strip()
            normalized_path = path.replace("\\", "/")
            if normalized_path.split("/", 1)[0].lower() == "manual":
                continue
            if synthetic_prefix is not None and not normalized_path.startswith(synthetic_prefix):
                continue
            if path and text:
                yield path, text


def reference_label(ref: Path, reference_dirs: list[Path]) -> str:
    if len(reference_dirs) == 1:
        try:
            return str(ref.relative_to(reference_dirs[0]))
        except ValueError:
            return str(ref)

    for reference_dir in reference_dirs:
        try:
            return str(Path(reference_dir.name) / ref.relative_to(reference_dir))
        except ValueError:
            continue
    return str(ref)


def speaker_dir_name(ref_label: str) -> str:
    """Speaker directory for a reference label: "jp/speaker_079_x.mp3" -> "speaker_079_x"."""
    return Path(ref_label.replace("\\", "/")).stem


def speaker_output_rel_path(rel_path: str, ref_label: str) -> str:
    """Place flat synthetic paths inside the reference speaker's subdirectory.

    Rows spliced into data-pairs.csv before generation look like
    synthetic/cs-1/cs151.flac; generated audio must land at
    synthetic/cs-1/<speaker>/cs151.flac so dataset splits stay speaker-disjoint.
    Paths that already contain a speaker directory are returned unchanged.
    """
    normalized = rel_path.replace("\\", "/")
    parts = normalized.split("/")
    if parts[0] == "synthetic" and len(parts) == 3:
        return "/".join([parts[0], parts[1], speaker_dir_name(ref_label), parts[2]])
    return rel_path


def update_pairs_csv_paths(csv_path: Path, out_root: Path, has_header: bool) -> int:
    """Rewrite flat synthetic CSV rows to the speaker subdirectory their audio landed in."""
    lines = csv_path.read_text(encoding="utf-8").splitlines()
    updated = 0
    for i in range(1 if has_header else 0, len(lines)):
        path, sep, rest = lines[i].partition("|")
        if not sep:
            continue
        normalized = path.strip().replace("\\", "/")
        parts = normalized.split("/")
        if len(parts) != 3 or parts[0] != "synthetic" or (out_root / normalized).exists():
            continue
        matches = sorted((out_root / parts[0] / parts[1]).glob(f"*/{parts[2]}"))
        if len(matches) == 1:
            lines[i] = f"{matches[0].relative_to(out_root).as_posix()}|{rest}"
            updated += 1
    if updated:
        csv_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return updated


def write_debug_renders(wav_path: Path, result: SynthesisResult) -> None:
    base = wav_path.with_suffix("")
    for lang, audio in result.render_audio.items():
        render_wav_path = base.with_name(f"{base.name}.{lang}.render.wav")
        render_json_path = render_wav_path.with_suffix(".json")
        sf.write(str(render_wav_path), audio, TARGET_SR, subtype="PCM_16")
        render_json_path.write_text(
            json.dumps(
                {
                    "audio_path": str(render_wav_path),
                    "sample_rate": TARGET_SR,
                    **result.renders[lang],
                },
                ensure_ascii=False,
                indent=2,
            ),
            encoding="utf-8",
        )


# ---- Main -------------------------------------------------------------------


def run_generation(args: argparse.Namespace, worker_index: int = 0, worker_count: int = 1) -> tuple[int, int, int]:
    reference_dirs = [p.resolve() for p in args.references]
    seed_everything(args.seed + worker_index)
    synth = XTTSCodeSwitchSynthesizer(reference_dirs, device=args.device, align_device=args.align_device)
    worker_label = f"worker {worker_index + 1}/{worker_count}: " if worker_count > 1 else ""
    print(
        f"{worker_label}Loaded XTTS v2 on {args.device} + MMS_FA aligner on {args.align_device}; "
        f"{len(synth.references)} reference clips across {len(reference_dirs)} reference dir(s)."
    )

    rows = list(iter_rows(args.csv, args.has_header, args.synthetic_folder))
    if not rows:
        print("No rows to process.", file=sys.stderr)
        return 0, 0, 0

    ok = failures = skipped = 0
    for i, (rel_path, sentence) in enumerate(rows, 1):
        if (i - 1) % worker_count != worker_index:
            continue

        row_seed = args.seed + i
        ref = synth.pick_reference(random.Random(row_seed))
        ref_label = reference_label(ref, reference_dirs)
        rel_path = speaker_output_rel_path(rel_path, ref_label)

        wav_path = args.out_root / rel_path
        json_path = wav_path.with_suffix(".json")

        if args.skip_existing and wav_path.exists() and json_path.exists():
            print(f"{worker_label}[{i}/{len(rows)}] SKIP   {rel_path}")
            skipped += 1
            continue

        wav_path.parent.mkdir(parents=True, exist_ok=True)

        try:
            seed_everything(row_seed)
            result = synth.synthesize(sentence, ref)
            audio = result.audio
            spans = result.spans
            if audio.size == 0:
                print(f"{worker_label}[{i}/{len(rows)}] EMPTY  {rel_path}")
                failures += 1
                continue

            sf.write(str(wav_path), audio, TARGET_SR, subtype="PCM_16")
            if args.debug_renders:
                write_debug_renders(wav_path, result)

            span_tuples = [(s["start_sample"], s["end_sample"], s["lang"]) for s in spans]

            sidecar = {
                "audio_path": str(rel_path),
                "sentence": sentence,
                "sample_rate": TARGET_SR,
                "duration_ms": int(round(audio.size / TARGET_SR * 1000)),
                "reference_speaker": ref_label,
                "seed": row_seed,
                "tts_language": result.tts_language,
                "alignment": result.alignment,
                "spans": spans,
                "renders": result.renders,
                "frame_rate_hz": FRAME_RATE_HZ,
                "num_frames": (audio.size + FRAME_STRIDE - 1) // FRAME_STRIDE,
                "frame_labels": _frame_labels(
                    span_tuples,
                    audio.size,
                    args.boundary_ambig_ms,
                ),
            }
            json_path.write_text(
                json.dumps(sidecar, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

            ok += 1
            print(
                f"{worker_label}[{i}/{len(rows)}] OK     {rel_path}  ref={ref.name}  lang={result.tts_language}  "
                f"align={result.alignment}  {audio.size / TARGET_SR:.2f}s {len(spans)} span(s)"
            )
        except Exception as e:  # noqa: BLE001 — log and move on
            print(f"{worker_label}[{i}/{len(rows)}] FAIL   {rel_path}: {e}", file=sys.stderr)
            failures += 1

    print(f"\n{worker_label}Done. {ok} generated, {skipped} skipped, {failures} failed.")
    return ok, skipped, failures


def run_generation_workers(args: argparse.Namespace) -> int:
    ctx = mp.get_context("spawn")
    processes = [
        ctx.Process(target=run_generation, args=(args, worker_index, args.workers))
        for worker_index in range(args.workers)
    ]
    for process in processes:
        process.start()
    for process in processes:
        process.join()

    failed = [process.exitcode for process in processes if process.exitcode]
    if failed:
        print(f"{len(failed)} worker process(es) failed: {failed}", file=sys.stderr)
        return 1
    return 0


def main():
    ap = argparse.ArgumentParser(
        description="Generate same-speaker EN/JA code-switched audio + frame labels via XTTS v2."
    )
    ap.add_argument("csv", type=Path, help="Pipe-delimited CSV: path | sentence")
    ap.add_argument(
        "--references",
        type=Path,
        nargs="+",
        required=True,
        help="One or more directories of reference speaker clips (.wav/.mp3/.flac, 3-10s ideal)",
    )
    ap.add_argument("--out-root", type=Path, default=Path("."), help="Base dir CSV paths resolve against")
    ap.add_argument("--has-header", action="store_true")
    ap.add_argument(
        "--synthetic-folder",
        help=(
            "Only generate rows under this synthetic folder. Accepts values like "
            "'en', 'cs-2', 'synthetic/en', or 'data/synthetic/en'."
        ),
    )
    ap.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Base seed for reference selection and per-row TTS sampling",
    )
    ap.add_argument("--device", default="cuda", help="cuda / cpu / mps (XTTS)")
    ap.add_argument(
        "--align-device",
        default="cpu",
        help="Device for the MMS_FA forced aligner (cpu is fast enough and avoids mps op gaps)",
    )
    ap.add_argument("--skip-existing", action="store_true", help="Skip rows whose WAV and JSON both already exist")
    ap.add_argument(
        "--debug-renders",
        action="store_true",
        help="Write intermediate full-sentence render WAV/JSON files next to each final output",
    )
    ap.add_argument(
        "--boundary-ambig-ms",
        type=int,
        default=0,
        help="Mark frame labels within +/- this many ms of a language switch as 'a'",
    )
    ap.add_argument(
        "--workers",
        type=int,
        default=1,
        help="Number of independent generator processes. Each worker loads its own XTTS model.",
    )
    args = ap.parse_args()

    if not args.csv.exists():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        sys.exit(1)
    reference_dirs = [p.resolve() for p in args.references]
    missing_reference_dirs = [p for p in reference_dirs if not p.is_dir()]
    if missing_reference_dirs:
        print(
            "References dir not found: " + ", ".join(str(p) for p in missing_reference_dirs),
            file=sys.stderr,
        )
        sys.exit(1)

    if args.workers < 1:
        print("--workers must be >= 1", file=sys.stderr)
        sys.exit(1)
    if args.workers == 1:
        run_generation(args)
    else:
        exit_code = run_generation_workers(args)
        if exit_code:
            sys.exit(exit_code)

    updated = update_pairs_csv_paths(args.csv, args.out_root, args.has_header)
    if updated:
        print(f"Updated {updated} row(s) in {args.csv} to per-speaker paths.")


if __name__ == "__main__":
    main()
