"""
Generate same-speaker code-switched EN/JA audio + frame-level language labels.

Uses XTTS v2 (Coqui) with voice cloning: a single reference speaker clip is
held across every language switch inside a sentence, so the resulting audio
is true same-speaker code-switching — the speaker timbre stays stable while
the language flips. This matches real EN<->JA code-switching far better than
stitched clips from different speakers.

CSV format (no header by default; pass --has-header if yours has one):
    path/to/output.wav | the sentence to encode, 日本語 included
    path/to/other.wav  | another sentence

Outputs per row:
    {out-root}/{path}.wav     — mono 16-bit PCM at TARGET_SR
    {out-root}/{path}.json    — span boundaries + frame-level language labels

Sidecar JSON shape:
    {
      "audio_path": "...",
      "sentence": "...",
      "sample_rate": 16000,
      "duration_ms": 2345,
      "reference_speaker": "ref_0037.wav",
      "spans": [
        {"lang": "en", "text": "Hello,", "start_ms": 0, "end_ms": 850,
         "start_sample": 0, "end_sample": 13600},
        ...
      ],
      "frame_rate_hz": 50,
      "num_frames": 117,
      "frame_labels": "eeee...jjjj..."   # 'e'=EN, 'j'=JA, 'a'=ambiguous boundary
    }

Requirements:
    pip install coqui-tts soundfile python-dotenv numpy torch
    # or the maintained community fork:
    pip install git+https://github.com/idiap/coqui-ai-TTS

License caveat: XTTS v2 ships under the Coqui Public Model License (CPML) —
non-commercial use only. Audio generated by this script is fine for research
and training internal evaluation models; if your final LID router will ship
commercially, plan to regenerate the training set with a permissively-licensed
backend (or accept that the audio data lineage may limit downstream rights)
before launch.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterator

import numpy as np
import soundfile as sf
import torch
from dotenv import load_dotenv
from TTS.api import TTS

load_dotenv()  # Parity with the rest of your project; not consumed here.

# ---- Configuration ----------------------------------------------------------

XTTS_MODEL = "tts_models/multilingual/multi-dataset/xtts_v2"
XTTS_SR = 24_000
TARGET_SR = 16_000  # wav2vec2-base expects 16 kHz mono
FRAME_RATE_HZ = 50  # wav2vec2-base outputs 50 frames/sec
FRAME_STRIDE = TARGET_SR // FRAME_RATE_HZ  # 320 samples per frame

CROSSFADE_MS = 8
CROSSFADE_SAMPLES = int(TARGET_SR * CROSSFADE_MS / 1000)

LANG_TO_CHAR = {"en": "e", "ja": "j"}

# Unicode ranges for Japanese script. ASCII letters cover English.
JA_CHAR_RE = re.compile(
    r"[\u3040-\u309F"  # Hiragana
    r"\u30A0-\u30FF"  # Katakana
    r"\u4E00-\u9FFF"  # CJK Unified Ideographs (Kanji)
    r"\u3400-\u4DBF"  # CJK Extension A
    r"\uFF66-\uFF9F]"  # Halfwidth Katakana
)
LATIN_CHAR_RE = re.compile(r"[A-Za-z]")


# ---- Span detection ---------------------------------------------------------


@dataclass
class Span:
    text: str
    lang: str  # "en" or "ja"


def detect_spans(sentence: str) -> list[Span]:
    """Split a sentence into contiguous EN / JA runs.

    Punctuation, digits, and whitespace attach to the preceding language span
    (or the next one if they lead the sentence) so trailing commas, question
    marks, and 。 stay with the span that produced them — TTS prosody depends
    on this.
    """
    char_lang = []
    for ch in sentence:
        if JA_CHAR_RE.match(ch):
            char_lang.append("ja")
        elif LATIN_CHAR_RE.match(ch):
            char_lang.append("en")
        else:
            char_lang.append("neutral")

    first_real = next((l for l in char_lang if l != "neutral"), "en")
    resolved = []
    last_real = first_real
    for lang in char_lang:
        if lang == "neutral":
            resolved.append(last_real)
        else:
            last_real = lang
            resolved.append(lang)

    spans: list[Span] = []
    buf = ""
    cur = resolved[0] if resolved else "en"
    for ch, lang in zip(sentence, resolved):
        if lang == cur:
            buf += ch
        else:
            spans.append(Span(text=buf, lang=cur))
            buf = ch
            cur = lang
    if buf:
        spans.append(Span(text=buf, lang=cur))

    return [Span(text=s.text.strip(), lang=s.lang) for s in spans if s.text.strip()]


# ---- Audio utilities --------------------------------------------------------


def _resample(audio: np.ndarray, src_sr: int, dst_sr: int) -> np.ndarray:
    """Linear resample. Swap to librosa.resample / torchaudio for higher quality."""
    if src_sr == dst_sr or audio.size == 0:
        return audio
    duration = audio.size / src_sr
    dst_samples = int(round(duration * dst_sr))
    x_src = np.linspace(0, duration, audio.size, endpoint=False)
    x_dst = np.linspace(0, duration, dst_samples, endpoint=False)
    return np.interp(x_dst, x_src, audio).astype(np.float32)


def _peak_normalize(audio: np.ndarray, peak: float = 0.95) -> np.ndarray:
    if audio.size == 0:
        return audio
    m = float(np.max(np.abs(audio)))
    if m < 1e-6:
        return audio
    return (audio * (peak / m)).astype(np.float32)


def _crossfade_concat(
    chunks: list[np.ndarray],
    xf: int,
) -> tuple[np.ndarray, list[int]]:
    """Crossfade-concat chunks and return (audio, span_end_samples).

    span_end_samples[i] is the sample index (in the final audio) where span i
    ends — taken at the midpoint of the crossfade so the label split divides
    the fade region evenly.
    """
    if not chunks:
        return np.zeros(0, dtype=np.float32), []
    if len(chunks) == 1:
        return chunks[0], [chunks[0].size]

    out = chunks[0].copy()
    end_samples: list[int] = []
    for nxt in chunks[1:]:
        n = min(xf, out.size, nxt.size)
        if n == 0:
            end_samples.append(out.size)
            out = np.concatenate([out, nxt])
            continue
        fade_out = np.linspace(1.0, 0.0, n, dtype=np.float32)
        fade_in = np.linspace(0.0, 1.0, n, dtype=np.float32)
        mixed = out[-n:] * fade_out + nxt[:n] * fade_in
        end_samples.append(out.size - n + n // 2)
        out = np.concatenate([out[:-n], mixed, nxt[n:]])
    end_samples.append(out.size)
    return out, end_samples


def _find_lang_at(center: int, spans: list[tuple[int, int, str]]) -> str:
    for start, end, lang in spans:
        if start <= center < end:
            return lang
    return spans[-1][2] if spans else "en"


def _frame_labels(
    spans: list[tuple[int, int, str]],
    total_samples: int,
    boundary_ambig_ms: int = 0,
) -> str:
    """One char per frame at FRAME_RATE_HZ.

    For each frame, the label is the language of the span containing the
    frame's center sample. If ``boundary_ambig_ms`` > 0, frames whose centers
    fall within that window of a language switch are labeled 'a' (ambiguous).
    """
    boundary_ambig_samples = int(boundary_ambig_ms * TARGET_SR / 1000)
    num_frames = (total_samples + FRAME_STRIDE - 1) // FRAME_STRIDE

    # Span boundaries = starts of spans 2..N (i.e. switch points).
    switch_points = [s[0] for s in spans[1:]]

    labels: list[str] = []
    for f in range(num_frames):
        center = f * FRAME_STRIDE + FRAME_STRIDE // 2
        if boundary_ambig_samples > 0 and any(abs(center - sp) <= boundary_ambig_samples for sp in switch_points):
            labels.append("a")
        else:
            labels.append(LANG_TO_CHAR[_find_lang_at(center, spans)])
    return "".join(labels)


# ---- Synthesizer ------------------------------------------------------------


class XTTSCodeSwitchSynthesizer:
    """XTTS v2 wrapper that holds a per-sentence speaker reference across
    EN <-> JA switches and caches speaker latents per reference clip.
    """

    def __init__(self, reference_dir: Path, device: str = "cuda"):
        # If running headless, set COQUI_TOS_AGREED=1 before launching to
        # bypass the interactive model-license prompt on first download.
        self.tts = TTS(XTTS_MODEL)
        self.tts.to(device)
        self.model = self.tts.synthesizer.tts_model

        exts = {".wav", ".mp3", ".flac"}
        self.references = sorted(p for p in reference_dir.glob("*") if p.suffix.lower() in exts)
        if not self.references:
            raise FileNotFoundError(f"No reference clips (.wav/.mp3/.flac) found in {reference_dir}")
        self._latent_cache: dict[Path, tuple] = {}

    def pick_reference(self, rng: random.Random) -> Path:
        return rng.choice(self.references)

    def _get_latents(self, ref_path: Path):
        cached = self._latent_cache.get(ref_path)
        if cached is not None:
            return cached
        gpt, spk = self.model.get_conditioning_latents(audio_path=[str(ref_path)])
        self._latent_cache[ref_path] = (gpt, spk)
        return gpt, spk

    def _generate_span(self, text: str, lang: str, ref_path: Path) -> np.ndarray:
        gpt_cond_latent, speaker_embedding = self._get_latents(ref_path)
        out = self.model.inference(
            text=text,
            language=lang,
            gpt_cond_latent=gpt_cond_latent,
            speaker_embedding=speaker_embedding,
            temperature=0.7,
        )
        wav = out["wav"]
        if isinstance(wav, torch.Tensor):
            wav = wav.cpu().numpy()
        return np.asarray(wav, dtype=np.float32)

    def synthesize(
        self,
        sentence: str,
        ref_path: Path,
    ) -> tuple[np.ndarray, list[dict]]:
        """Return (audio_16k, span_records).

        Each span record: lang, text, start_ms, end_ms, start_sample, end_sample.
        """
        spans = detect_spans(sentence)
        if not spans:
            return np.zeros(0, dtype=np.float32), []

        per_span_audio: list[np.ndarray] = []
        for span in spans:
            audio_24k = self._generate_span(span.text, span.lang, ref_path)
            audio_16k = _resample(audio_24k, XTTS_SR, TARGET_SR)
            audio_16k = _peak_normalize(audio_16k)
            per_span_audio.append(audio_16k)

        full_audio, end_samples = _crossfade_concat(per_span_audio, CROSSFADE_SAMPLES)

        records: list[dict] = []
        prev = 0
        for span, end_sample in zip(spans, end_samples):
            records.append(
                {
                    "lang": span.lang,
                    "text": span.text,
                    "start_sample": prev,
                    "end_sample": end_sample,
                    "start_ms": int(round(prev / TARGET_SR * 1000)),
                    "end_ms": int(round(end_sample / TARGET_SR * 1000)),
                }
            )
            prev = end_sample
        return full_audio, records


# ---- CSV iteration ----------------------------------------------------------


def iter_rows(csv_path: Path, has_header: bool) -> Iterator[tuple[str, str]]:
    with csv_path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter="|")
        if has_header:
            next(reader, None)
        for row in reader:
            if len(row) < 2:
                continue
            path = row[0].strip()
            text = row[1].strip()
            if path and text:
                yield path, text


# ---- Main -------------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser(
        description="Generate same-speaker EN/JA code-switched audio + frame labels via XTTS v2."
    )
    ap.add_argument("csv", type=Path, help="Pipe-delimited CSV: path | sentence")
    ap.add_argument(
        "--references",
        type=Path,
        required=True,
        help="Directory of reference speaker clips (.wav/.mp3/.flac, 3-10s ideal)",
    )
    ap.add_argument("--out-root", type=Path, default=Path("."), help="Base dir CSV paths resolve against")
    ap.add_argument("--has-header", action="store_true")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--device", default="cuda", help="cuda / cpu / mps")
    ap.add_argument("--skip-existing", action="store_true", help="Skip rows whose WAV and JSON both already exist")
    ap.add_argument(
        "--boundary-ambig-ms",
        type=int,
        default=0,
        help="Mark frame labels within +/- this many ms of a language switch as 'a'",
    )
    args = ap.parse_args()

    if not args.csv.exists():
        print(f"CSV not found: {args.csv}", file=sys.stderr)
        sys.exit(1)
    if not args.references.exists():
        print(f"References dir not found: {args.references}", file=sys.stderr)
        sys.exit(1)

    rng = random.Random(args.seed)
    synth = XTTSCodeSwitchSynthesizer(args.references, device=args.device)
    print(f"Loaded XTTS v2 on {args.device}; {len(synth.references)} reference clips available.")

    rows = list(iter_rows(args.csv, args.has_header))
    if not rows:
        print("No rows to process.", file=sys.stderr)
        sys.exit(0)

    ok = failures = skipped = 0
    for i, (rel_path, sentence) in enumerate(rows, 1):
        wav_path = args.out_root / rel_path
        json_path = wav_path.with_suffix(".json")

        if args.skip_existing and wav_path.exists() and json_path.exists():
            print(f"[{i}/{len(rows)}] SKIP   {rel_path}")
            skipped += 1
            continue

        wav_path.parent.mkdir(parents=True, exist_ok=True)
        ref = synth.pick_reference(rng)

        try:
            audio, spans = synth.synthesize(sentence, ref)
            if audio.size == 0:
                print(f"[{i}/{len(rows)}] EMPTY  {rel_path}")
                failures += 1
                continue

            sf.write(str(wav_path), audio, TARGET_SR, subtype="PCM_16")

            span_tuples = [(s["start_sample"], s["end_sample"], s["lang"]) for s in spans]
            try:
                ref_label = str(ref.relative_to(args.references))
            except ValueError:
                ref_label = str(ref)

            sidecar = {
                "audio_path": str(rel_path),
                "sentence": sentence,
                "sample_rate": TARGET_SR,
                "duration_ms": int(round(audio.size / TARGET_SR * 1000)),
                "reference_speaker": ref_label,
                "spans": spans,
                "frame_rate_hz": FRAME_RATE_HZ,
                "num_frames": (audio.size + FRAME_STRIDE - 1) // FRAME_STRIDE,
                "frame_labels": _frame_labels(
                    span_tuples,
                    audio.size,
                    args.boundary_ambig_ms,
                ),
            }
            json_path.write_text(
                json.dumps(sidecar, ensure_ascii=False, indent=2),
                encoding="utf-8",
            )

            ok += 1
            print(
                f"[{i}/{len(rows)}] OK     {rel_path}  ref={ref.name}  "
                f"{audio.size / TARGET_SR:.2f}s {len(spans)} span(s)"
            )
        except Exception as e:  # noqa: BLE001 — log and move on
            print(f"[{i}/{len(rows)}] FAIL   {rel_path}: {e}", file=sys.stderr)
            failures += 1

    print(f"\nDone. {ok} generated, {skipped} skipped, {failures} failed.")


if __name__ == "__main__":
    main()
